### ISSUE TITLE
Oracle Syntax: `BIS_S_DBOWNER`

### ISSUE THREAD

**Issue by iversond** [accasey/PSDbPrivs#2]
Add Oracle-specific SQL for this object. Need to as the table owner for `psdbowner` in Oracle:

```sql
SELECT OWNERID FROM PS.PSDBOWNER WHERE 1=1 AND DBNAME=:1
```

**Comment by accasey** [comment]
There should actually be a public synonym so PSDBOWNER will work. But yes, it should be Oracle as the DB type. Although that would probably require a little rework.

**Comment by accasey** [comment]
This is really only used to show the table owner, and isn't really used. It would be better (I think) to hide the column. Otherwise you need to get into the DB2 version of the SQL as well..

**Comment by iversond** [comment]
Tested again and the script worked.
