### ISSUE TITLE
Page to exclude system accounts from Grant management

### ISSUE THREAD

**Issue by iversond** [accasey/PSDbPrivs#5]
Possible enhancement to the tool - allow an exclusion (or inclusion) list of users to manage. Currently all database Grantees are loaded and managed, but some orgs may want to only manage the db privileges only for  the PeopleSoft-related accounts.

**Comment by accasey** [comment]
I will build a simple page, much like the record lookup exclusion page, where you can list the Grantee(s) you want to exclude.

I'll modify the search page on the main page so you can add a Grantee that's on the table.

I'll modify the main view (with the pivot) to exclude from this table as well.

**Comment by iversond** [comment]
Exclusion page looks good.
